# Generated by Django 6.0.3 on 2026-03-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_laser_minuto', models.DecimalField(decimal_places=2, default=15.0, max_digits=8, verbose_name='Tarifa láser por minuto ($)')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Precios',
                'verbose_name_plural': 'Configuración de Precios',
                'db_table': 'configuracion_precios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_utilidad', models.IntegerField()),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabuladorCostos',
            fields=[
                ('id_tabulador', models.AutoField(primary_key=True, serialize=False)),
                ('espesor_mm', models.IntegerField()),
                ('factor_costo', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tabulador_Costo',
                'verbose_name_plural': 'Tabulador_Costos',
                'db_table': 'tabulador_costos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('largo_pza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_pza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minutos_lazer', models.IntegerField(blank=True, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.clientes')),
                ('id_material', models.ForeignKey(blank=True, db_column='id_material', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.materiales')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.productos')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estatus', models.CharField(choices=[('en_produccion', 'En producción'), ('pagada', 'Pagada'), ('entregada', 'Entregada')], default='en_produccion', max_length=20)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_venta', models.DateField(auto_now_add=True, null=True)),
                ('id_cotizacion', models.ForeignKey(blank=True, db_column='id_cotizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.cotizaciones')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'managed': True,
            },
        ),
    ]
