# Generated by Django 6.0.3 on 2026-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En producción'), ('pagada', 'Pagada'), ('entregada', 'Entregada')], default='pendiente', max_length=20),
        ),
    ]
