# Generated by Django 6.0.3 on 2026-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agregar_estado_pendiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='monto_pagado',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='espesor_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Espesor (mm)'),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='porcentaje_utilidad',
            field=models.IntegerField(default=40, verbose_name='Utilidad (%)'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Fijo (Opcional)'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Anticipo/Abono'),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='ancho_pza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='largo_pza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largo (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='porcentaje_utilidad',
            field=models.IntegerField(default=40),
        ),
    ]
