# Generated by Django 6.0.3 on 2026-05-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_ventas_monto_pagado_cotizaciones_espesor_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('largo_pza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_pza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espesor_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minutos_lazer', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materiales')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.productos')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
