# Generated by Django 6.0.3 on 2026-05-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_detalleventa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={},
        ),
        migrations.AlterModelTable(
            name='ventas',
            table=None,
        ),
    ]
