# Generated by Django 6.0.3 on 2026-06-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006 ventas id cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(choices=[('cotizacion', 'Cotización'), ('pendiente', 'Pendiente'), ('en_produccion', 'En producción'), ('pagada', 'Pagada'), ('entregada', 'Entregada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente_directo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.clientes'),
        ),
    ]
