# Generated by Django 6.0.3 on 2026-06-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_ventas_estatus_alter_ventas_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.materiales'),
        ),
    ]
