# Generated by Django 6.0.3 on 2026-07-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_detalleventa_id_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
    ]
