# Generated by Django 6.0.3 on 2026-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_productos_stock_actual_productos_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ventas',
            name='incluye_iva',
            field=models.BooleanField(default=False),
        ),
    ]
